### ISSUE TITLE
Create a standard library for our projects

### ISSUE THREAD

**Issue by aqrln** [metarhia/Metarhia#2]
Impress and JSTP already have a handful of equivalent functions it their sources, and clearly GlobalStorage and other projects will do too. It is worth to decouple them into a separate package and thus create the missing standard library for JavaScript.

**Comment by tshemsedinov** [comment]
Now Impress have something like this in `/lib/api.common.js`

**Comment by aqrln** [comment]
@tshemsedinov, yes, and JSTP has analogous module, too. Moreover, some of their functions overlap between these projects. That's why I think we should decouple them from both to simplify maintenance and to allow them to be used in other projects.

**Comment by tshemsedinov** [comment]
https://github.com/metarhia/Common
