### ISSUE TITLE
Drop 6, 9 node.js support

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Metarhia#20]
When can we drop support 6, 8, and 9 node.js support? What do you think? It will be good for globalstorage implementation (no fallbacks or multiple implementations for optimized functions, use classes, etc.) @aqrln @belochub @nechaido @lundibundi

**Comment by lundibundi** [comment]
I think we can definitely drop 9 and maybe 6 as it's quite old though still in maintenance until mid-2019. As for 8, I don't think we should drop it, it will still be actively supported until mid-2019, furthermore, it's current LTS.
For accurate dates see the link.
Refs: https://github.com/nodejs/Release

**Comment by tshemsedinov** [comment]
@lundibundi I know that link but we need BigInt, N-API, new v8 performance optimizations etc. Now BigInt will become key requirement for globalstorage. Implementing globalstorage we will closely integrate it with impress: globalstorage object identification requires changes in impress cluster implementation. I don't like polyfills in performance critical features. On the other hand we have users who can't move to node 10 quickly.

**Comment by tshemsedinov** [comment]
At least we need to drop `6.x` in all libraries, including CI and `package.json` field `"engines": { "node": ">=6.0.0" }`. Please @belochub @nechaido @lundibundi ask our team to do that.

**Comment by nechaido** [comment]
I am perfectly fine with not supporting any version prior to `10`, but I'd prefer to only drop the support when we need a particular feature that is not implemented in earlier Node.js versions.

**Comment by tshemsedinov** [comment]
We can drop 6 and 9 but support 8 till we port impress to worker_threads and then we will use only 11 and later.

**Comment by lundibundi** [comment]
Considering it's now named `Drop 6, 9 ...` I think we can close it since they are EOF already and can be freely removed from our repos if they are still present.

/cc @tshemsedinov
