### ISSUE TITLE
Use raw badges from service providers

### ISSUE THREAD

**Issue by aqrln** [metarhia/Metarhia#3]
shields.io seems unreliable. Over a couple of weeks shields have been taking quite a long time to load and about half of them, and sometimes all of them, haven't been loading at all.

![image](https://cloud.githubusercontent.com/assets/4923335/22833743/b9f3d444-efbb-11e6-9d67-d52d44ad6856.png)

/cc @tshemsedinov

**Comment by aqrln** [comment]
@tshemsedinov, I think squared badges that load well are better than flat badges that don't load at all.

**Comment by tshemsedinov** [comment]
Done
