### ISSUE TITLE
Grant access to the `tickplate` repo for the Inquisitori team

### ISSUE THREAD

**Issue by aqrln** [metarhia/Metarhia#4]
[tickplate](https://github.com/metarhia/tickplate) is the only repository @metarhia/inquisitori team has no write access to. Since it is a new repo in the Metarhia family, I suppose it was omitted forgetfully so the proposal is to add it to [the list](https://github.com/orgs/metarhia/teams/inquisitori/repositories).

/cc @tshemsedinov

**Comment by tshemsedinov** [comment]
Done
