### ISSUE TITLE
Mobile file exchange and chat mobile application example

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Metarhia#9]
We have web version of this app, but after https://github.com/metarhia/Server/issues/5 and https://github.com/metarhia/Server/issues/11 we need to create mobile app. I don't remember what we have here https://github.com/metarhia/Messenger can we use this repo or we need new one? Or maybe separate for iOS and Android?
@metarhia/angeli @metarhia/amici

**Comment by GYFK** [comment]
@tshemsedinov we better use separate repos for iOS and Android like Messenger-iOS and Messenger-Android and add both repos as submodules to the the original Messenger repo.

**Comment by tshemsedinov** [comment]
https://github.com/metarhia/MetaCom-iOS
https://github.com/metarhia/MetaCom-Android

**Comment by tshemsedinov** [comment]
1. Functionality is equal to web version, you can get it from https://github.com/metarhia/Server start and open in browser by http://127.0.0.1/console then use commands `upload`, `download` and `chat`.
2. Now we use Web Sockets, but mobile version will use only JSTP so waiting server-side implementation.
3. Before that you can prepare UI for:
- Settings: server host, port
- File upload and download not in chat (store to disk on server and get download code)
- Chat
- File upload and download in chat (do not store to disk and re-translate over memory)

@metarhia/mobile

**Comment by lidaamber** [comment]
@tshemsedinov just to get better understanding of application concept, could you review my vision of application and answer a few questions, please?
As far as I understand, MetaCom application features are achieved only after entering server host and port. 
* Can users communicate in several chats simultaneously?
* Are files uploaded not in chat reachable for other users? If yes, do we need to show any information about person who uploaded it? 
* Does user need to enter a download code to see and download the file? Or does user see the list of available files and enter the code to download certain file?
* Does every chat participant get the download code and file identifier when some user uploads the file?
* Do users need any nicks? Or should we display their identifiers in dialogues?
* Do we need to display a list of downloaded files for the quick access to them?

**Comment by tshemsedinov** [comment]
Version 1:
- Single chat at a time;
- Files uploaded not in chat will be stored at hd and we will give user a code to download; no additional info, no filename or dare/time, no even file type, absolute anonymity: no user;
- No file listing; all and only you need to download is a code; file will be automatically deleted after downloading;
- Chat will contain only two users; even not a users but anonymous connections, so we have no identification now; chat participants will not get a code after uploading; if one uploads a file in a chat it will be immediately transmitted to second participant and downloaded without a code;
- No nicks, no identification other then connections; you may mark messages just with colors;
- After downloading we will just store file locally and will not store their names/paths;
- We will not store history on client and on server;
@metarhia/mobile

**Comment by lidaamber** [comment]
@tshemsedinov thanks
What happens when the third person tries to join the chat? Or is this situation impossible?

**Comment by tshemsedinov** [comment]
@lidaamber after 2 persons joined, third cant join. Chat have a name, it can be used to access a chat, as a key.

**Comment by tshemsedinov** [comment]
Some answers requested by @GYFK
- We have no authenticated users at the system, if I say `user` it means `connection` (that's for anonymity);
- When I say `chat` means `chat room`;
- Chat can contain only two users and each user can be in a single chat at once;
- Interface should be as simple, common and conventional as possible;
@metarhia/mobile 
If you have more question plz ask me here @GYFK

**Comment by lidaamber** [comment]
Created a mock describing the main functionality of the first app version: https://ninjamock.com/s/DJXGC

Platform-specific designs and issues will be prepared and discussed in separate repositories.

**Comment by GYFK** [comment]
Both examples for iOS and Android were successfully implemented and published to stores.
Congrats @metarhia/server @metarhia/ios @metarhia/android
